package learning;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class VisualConceptLearner {
	public void classifyDatabase() {
		try {
			Process classification = new ProcessBuilder(
					"SemanticFeature/image_classification.exe", "data.txt")
					.start();
		} catch (IOException e) {
			System.out.println("Error calling image_classification.exe");
		}
		getPositiveScoreIndex();
	}

	/**
	 * Go through the results generated by image_classification.exe (txt files
	 * containing 1000 integers per image) and extract out index of concepts
	 * with positive score. Also generate compiled.txt which has all the scores for each
	 * img
	 */
	private void getPositiveScoreIndex() {
		// http://stackoverflow.com/questions/22347124/how-to-open-all-files-in-a-directory-in-java-read-them-creat-new-files-write
		String trainPath = "ImageData/train/data";
		File f = new File(trainPath);
		String[] fileList = f.list();
		String compiledString = "";
		Scanner scanner;
		BufferedWriter bw;

		for (String str : fileList) {
			if (str.endsWith(".txt")) {
				// Read the content of file "str" and store it in some variables
				int count = 1; // 1-based index
				String output = "";
				scanner = new Scanner(trainPath + str);

				while (scanner.hasNextDouble()) {
					double i = scanner.nextDouble();
					if (i > 0) {
						output += count + " ";
					}
					count++;
				}
				compiledString += str + " " + output + '\n';
				
				// now write the content in txt file
				try {
					bw = new BufferedWriter(new FileWriter(trainPath + str));
					bw.write(output); 
					bw.close();
				} catch (IOException e) {
					System.out.println("Cannot find " + trainPath + str);
				}
			}
		}
		
		try {
			bw = new BufferedWriter(new FileWriter(trainPath+"compiled.txt"));
			bw.write(compiledString);
			bw.close();
		} catch (IOException e) {
			System.out.println("Problem writing compiledString");
		}
		
	}
}
